stages:
  - lint
  - build
  - test
  - deploy
  
variables:
  # Set the maven local repository location to speed up builds by reusing cached dependencies
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

lint:
  stage: lint
  image: $CI_REGISTRY_IMAGE/ci:lint
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pre-commit run --all-files
  tags:
    - docker

# Build stage
build:
  stage: build
  image: maven:latest
  script:
    - mvn $MAVEN_OPTS clean package
  tags:
    - docker

# Test stage
test:
  stage: test
  image: maven:latest
  script:
    - mvn $MAVEN_OPTS test
  tags:
    - docker

# Deploy stage
deploy:
  stage: deploy
  image: adoptopenjdk:11-jre-hotspot
  script:
    - java -jar -Dspring.profiles.active=production target/DNDMapGen-0.0.1-SNAPSHOT.jar
  tags:
    - docker
  only:
    - master
